name: Test Case - OWASP 10

on:
  push:
  workflow_dispatch:

env:
  NIGHTVISION_TOKEN: ${{ secrets.NIGHTVISION_TOKEN }}
  NIGHTVISION_TARGET: owasp10
  NIGHTVISION_APP: owasp10
  NIGHTVISION_AUTH: owasp10
  APP: owasp10
  
jobs:
  test:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: (1) Clone Code
        uses: actions/checkout@v3
      
      - name: (2) Install NightVision
        run: |
          wget -c https://downloads.nightvision.net/binaries/latest/nightvision_latest_linux_amd64.tar.gz -O - | tar -xz; sudo mv nightvision /usr/local/bin/
          python -m pip install semgrep --user

      - name: (3) Extract API documentation from code
        run: |
          # for 0.4.0
          nightvision swagger extract ./ --lang python -t ${APP} || true
          if [ ! -e openapi-spec.yml ]; then
              cp backup-openapi-spec.yml openapi-spec.yml
          fi

      - name: (3.5) Upload openapi-spec documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec.yml
          path: openapi-spec.yml
          retention-days: 30

      - name: (4) Start the app
        run: docker-compose up -d; sleep 10

      - name: (5) Scan the API
        run: |
          nightvision scan -t ${NIGHTVISION_TARGET} -a ${NIGHTVISION_APP} --auth ${NIGHTVISION_AUTH} > scan-results.txt
          nightvision export sarif -s "$(head -n 1 scan-results.txt)" --swagger-file openapi-spec.yml


      - name: (5.1) Get logs
        run: for pod in $(docker ps | grep -v 'CONTAINER ID' | grep -v IMAGE | awk '{print $1}'); do docker logs $pod && docker logs $pod >> test.pod.logs 2>&1; done

      - name: (5.2) Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: test.pod.logs
          path: test.pod.logs
          retention-days: 30

      - name: (5.5) Upload sarif documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: results.sarif
          path: results.sarif
          retention-days: 30

      - name: (6) Upload SARIF file to GitHub Security Alerts if vulnerabilities are found
        uses: github/codeql-action/upload-sarif@v2
        if: success()
        with:
          sarif_file: results.sarif
